/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ToolRouteImport } from './routes/_tool'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ToolWhoisRouteImport } from './routes/_tool.whois'
import { Route as ToolSubdomainsRouteImport } from './routes/_tool.subdomains'
import { Route as ToolIpRouteImport } from './routes/_tool.ip'
import { Route as ToolEmailRouteImport } from './routes/_tool.email'
import { Route as ToolDnsRouteImport } from './routes/_tool.dns'

const ToolRoute = ToolRouteImport.update({
  id: '/_tool',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolWhoisRoute = ToolWhoisRouteImport.update({
  id: '/whois',
  path: '/whois',
  getParentRoute: () => ToolRoute,
} as any)
const ToolSubdomainsRoute = ToolSubdomainsRouteImport.update({
  id: '/subdomains',
  path: '/subdomains',
  getParentRoute: () => ToolRoute,
} as any)
const ToolIpRoute = ToolIpRouteImport.update({
  id: '/ip',
  path: '/ip',
  getParentRoute: () => ToolRoute,
} as any)
const ToolEmailRoute = ToolEmailRouteImport.update({
  id: '/email',
  path: '/email',
  getParentRoute: () => ToolRoute,
} as any)
const ToolDnsRoute = ToolDnsRouteImport.update({
  id: '/dns',
  path: '/dns',
  getParentRoute: () => ToolRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dns': typeof ToolDnsRoute
  '/email': typeof ToolEmailRoute
  '/ip': typeof ToolIpRoute
  '/subdomains': typeof ToolSubdomainsRoute
  '/whois': typeof ToolWhoisRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dns': typeof ToolDnsRoute
  '/email': typeof ToolEmailRoute
  '/ip': typeof ToolIpRoute
  '/subdomains': typeof ToolSubdomainsRoute
  '/whois': typeof ToolWhoisRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_tool': typeof ToolRouteWithChildren
  '/_tool/dns': typeof ToolDnsRoute
  '/_tool/email': typeof ToolEmailRoute
  '/_tool/ip': typeof ToolIpRoute
  '/_tool/subdomains': typeof ToolSubdomainsRoute
  '/_tool/whois': typeof ToolWhoisRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/dns' | '/email' | '/ip' | '/subdomains' | '/whois'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/dns' | '/email' | '/ip' | '/subdomains' | '/whois'
  id:
    | '__root__'
    | '/'
    | '/_tool'
    | '/_tool/dns'
    | '/_tool/email'
    | '/_tool/ip'
    | '/_tool/subdomains'
    | '/_tool/whois'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ToolRoute: typeof ToolRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_tool': {
      id: '/_tool'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof ToolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_tool/whois': {
      id: '/_tool/whois'
      path: '/whois'
      fullPath: '/whois'
      preLoaderRoute: typeof ToolWhoisRouteImport
      parentRoute: typeof ToolRoute
    }
    '/_tool/subdomains': {
      id: '/_tool/subdomains'
      path: '/subdomains'
      fullPath: '/subdomains'
      preLoaderRoute: typeof ToolSubdomainsRouteImport
      parentRoute: typeof ToolRoute
    }
    '/_tool/ip': {
      id: '/_tool/ip'
      path: '/ip'
      fullPath: '/ip'
      preLoaderRoute: typeof ToolIpRouteImport
      parentRoute: typeof ToolRoute
    }
    '/_tool/email': {
      id: '/_tool/email'
      path: '/email'
      fullPath: '/email'
      preLoaderRoute: typeof ToolEmailRouteImport
      parentRoute: typeof ToolRoute
    }
    '/_tool/dns': {
      id: '/_tool/dns'
      path: '/dns'
      fullPath: '/dns'
      preLoaderRoute: typeof ToolDnsRouteImport
      parentRoute: typeof ToolRoute
    }
  }
}

interface ToolRouteChildren {
  ToolDnsRoute: typeof ToolDnsRoute
  ToolEmailRoute: typeof ToolEmailRoute
  ToolIpRoute: typeof ToolIpRoute
  ToolSubdomainsRoute: typeof ToolSubdomainsRoute
  ToolWhoisRoute: typeof ToolWhoisRoute
}

const ToolRouteChildren: ToolRouteChildren = {
  ToolDnsRoute: ToolDnsRoute,
  ToolEmailRoute: ToolEmailRoute,
  ToolIpRoute: ToolIpRoute,
  ToolSubdomainsRoute: ToolSubdomainsRoute,
  ToolWhoisRoute: ToolWhoisRoute,
}

const ToolRouteWithChildren = ToolRoute._addFileChildren(ToolRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ToolRoute: ToolRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
